name: reactive_bloc
description: A dart package that provides a reactive way to work with BLoC pattern.
version: 0.0.1
repository: https://github.com/tremaze/reactive_bloc_dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
